name: "gleam update"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: gleam-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix flake update
        env:
          OUT: /tmp
          GH_TOKEN: ${{ github.token }}
          ASSIGNEE: vic
          GIT_AUTHOR_NAME: Victor Borja
          GIT_AUTHOR_EMAIL: vborja@apache.org
          GIT_COMMITTER_NAME: Victor Borja
          GIT_COMMITTER_EMAIL: vborja@apache.org
        run: nix develop .#hack-on-gleam-nix --accept-flake-config -c gh-flake-update
