name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Test flake output
      run: nix flake check
